import { ConstructorOptions } from 'audiomotion-analyzer';

export const configs = {
	authenticateUrl: 'https://dtizen-secure.vercel.app',
	relatedParagraphLength: 10000,
	createSalutationLength: 3000,
	salutationPrefixMessage: 'Hello! How can I help you?',
	vectorResultSimilarityScore: 0.75,
	closeVectorSimilarityScore: 0.2,
	promptTokenLimit: 10000,
	debateTokenLimit: 10000,
	uploadSizeLimit: '20mb',
};
export const visualizerOptions: ConstructorOptions = {
	width: 100,
	height: 100,
	alphaBars: false,
	ansiBands: false,
	barSpace: 0.1,
	bgAlpha: 0,
	// channelLayout: 'single',
	colorMode: 'gradient',
	fadePeaks: false,
	fftSize: 8192,
	fillAlpha: 0.6,
	frequencyScale: 'bark',
	gradient: 'prism',
	gravity: 3.8,
	ledBars: false,
	linearAmplitude: false,
	linearBoost: 1.6,
	lineWidth: 1.5,
	loRes: false,
	lumiBars: false,
	maxDecibels: -25,
	maxFPS: 0,
	maxFreq: 20000,
	minDecibels: -85,
	minFreq: 20,
	mirror: 0,
	mode: 5,
	noteLabels: false,
	outlineBars: false,
	overlay: true,
	peakFadeTime: 750,
	peakHoldTime: 500,
	peakLine: false,
	radial: true,
	radialInvert: false,
	radius: 0.3,
	reflexAlpha: 0.25,
	reflexBright: 1,
	reflexFit: true,
	reflexRatio: 0.3,
	roundBars: false,
	showBgColor: true,
	showFPS: false,
	showPeaks: true,
	showScaleX: true,
	showScaleY: false,
	smoothing: 0.5,
	spinSpeed: 1,
	splitGradient: false,
	trueLeds: false,
	useCanvas: true,
	volume: 1,
	weightingFilter: 'D',
};
