name: deploy-to-blob

on:
   push:
      branches:
         - master
   workflow_dispatch:

jobs:
   deploy-to-blob:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - name: npm install
           run: npm install
           shell: bash
         - name: npm run build
           run: npm run build
           env:
              API_ENDPOINT: https://chat4doc.com
              GOOGLE_CLIENT_ID: 53471127537-jlk6u6k67veppbr1t858e033qk744tc0.apps.googleusercontent.com
              KAKAO_CLIENT_ID: d178be7325e38f0545b134fae4e38cfc
              NAVER_CLIENT_ID: vSZhUBrETdcnS2U1hAmS
              APPLE_CLIENT_ID: com.talkdocu.service
              FACEBOOK_CLIENT_ID: 625046362996233
              ADSENSE_CLIENT: ca-pub-7554551043921031
              ADSENSE_SLOT : 7003703415
         - name: Log in to Azure
           uses: azure/login@v1
           with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}
         - name: Delete existing files in blob container
           uses: azure/CLI@v1.0.0
           with:
              azcliversion: 2.30.0
              inlineScript: |
                 az storage blob delete-batch --source '$web' --account-name jemishome --pattern '*'
                 sleep 10s  # Wait for the deletion to propagate

         # - name: Upload folder to blob
         #   uses: azure/CLI@v1.0.0
         #   with:
         #      azcliversion: 2.30.0
         #      inlineScript: |
         #         az storage blob upload-batch --destination '$web' --account-name jemishome --source out --overwrite=true
         - name: upload folder to blob
           uses: azure/cli@v1.0.0
           with:
              azcliver: 2.30.0
              inlineScript: |
                 az storage blob upload-batch \
                 --destination '$web' \
                 --account-name jemishome \
                 --source out \
              #   --overwrite=true
